spring:
  application:
    name: video-processing-service

server:
  port: 8083

app:
  storage:
    bucket: streaming-videos
    raw-prefix: raw
    processed-prefix: processed
    local-workdir: ./workdir

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  region: us-east-1

metadata:
  base-url: http://localhost:8081